In [195]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error
import numpy as np
import pickle

In [196]:
df = pd.read_csv('solar_flare.csv')
df.head()

flare  start.date start.time      peak       end  duration.s  peak.c/s  \
0  2021213  2002-02-12   21:29:56  21:33:38  21:41:48         712       136   
1  2021228  2002-02-12   21:44:08  21:45:06  21:48:56         288         7   
2  2021332  2002-02-13   00:53:24  00:54:54  00:57:00         216        15   
3  2021308  2002-02-13   04:22:52  04:23:50  04:26:56         244        20   
4  2021310  2002-02-13   07:03:52  07:05:14  07:07:48         236       336   

   total.counts energy.kev  x.pos.asec  y.pos.asec  radial  active.region.ar  \
0      167304.0      12-25         592        -358     692                 0   
1        9504.0       6-12         604        -341     694              9811   
2       11448.0       6-12        -310         375     487              9825   
3       17400.0      12-25        -277         378     469              9822   
4      313392.0      25-50        -272         390     476              9825   

  flag.1 flag.2 flag.3 flag.4 flag.5  
0     A1     P1    NaN    NaN    NaN  
1     A1     P1     PE     Q1    NaN  
2     A1     P1    NaN    NaN    NaN  
3     A1     P1    NaN    NaN    NaN  
4     A1     GS     P1     PE     Q2

In [197]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 116143 entries, 0 to 116142
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   flare             116143 non-null  int64  
 1   start.date        116143 non-null  object 
 2   start.time        116143 non-null  object 
 3   peak              116143 non-null  object 
 4   end               116143 non-null  object 
 5   duration.s        116143 non-null  int64  
 6   peak.c/s          116143 non-null  int64  
 7   total.counts      116143 non-null  float64
 8   energy.kev        116143 non-null  object 
 9   x.pos.asec        116143 non-null  int64  
 10  y.pos.asec        116143 non-null  int64  
 11  radial            116143 non-null  int64  
 12  active.region.ar  116143 non-null  int64  
 13  flag.1            116143 non-null  object 
 14  flag.2            116143 non-null  object 
 15  flag.3            96236 non-null   object 
 16  flag.4            95

In [198]:
df.isnull().sum()

flare                   0
start.date              0
start.time              0
peak                    0
end                     0
duration.s              0
peak.c/s                0
total.counts            0
energy.kev              0
x.pos.asec              0
y.pos.asec              0
radial                  0
active.region.ar        0
flag.1                  0
flag.2                  0
flag.3              19907
flag.4              20202
flag.5              61180
dtype: int64

In [199]:
df = df.drop(['flare','flag.1','flag.2','flag.3', 'flag.4', 'flag.5'], axis=1)

In [200]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 116143 entries, 0 to 116142
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   start.date        116143 non-null  object 
 1   start.time        116143 non-null  object 
 2   peak              116143 non-null  object 
 3   end               116143 non-null  object 
 4   duration.s        116143 non-null  int64  
 5   peak.c/s          116143 non-null  int64  
 6   total.counts      116143 non-null  float64
 7   energy.kev        116143 non-null  object 
 8   x.pos.asec        116143 non-null  int64  
 9   y.pos.asec        116143 non-null  int64  
 10  radial            116143 non-null  int64  
 11  active.region.ar  116143 non-null  int64  
dtypes: float64(1), int64(6), object(5)
memory usage: 10.6+ MB


In [201]:
df['start.time'] = pd.to_datetime(df['start.date'] + ' ' + df['start.time'])
df['peak'] = pd.to_datetime(df['start.date'] + ' ' + df['peak'])
df['end'] = pd.to_datetime(df['start.date'] + ' ' + df['end'])
df.head()

start.date          start.time                peak                 end  \
0  2002-02-12 2002-02-12 21:29:56 2002-02-12 21:33:38 2002-02-12 21:41:48   
1  2002-02-12 2002-02-12 21:44:08 2002-02-12 21:45:06 2002-02-12 21:48:56   
2  2002-02-13 2002-02-13 00:53:24 2002-02-13 00:54:54 2002-02-13 00:57:00   
3  2002-02-13 2002-02-13 04:22:52 2002-02-13 04:23:50 2002-02-13 04:26:56   
4  2002-02-13 2002-02-13 07:03:52 2002-02-13 07:05:14 2002-02-13 07:07:48   

   duration.s  peak.c/s  total.counts energy.kev  x.pos.asec  y.pos.asec  \
0         712       136      167304.0      12-25         592        -358   
1         288         7        9504.0       6-12         604        -341   
2         216        15       11448.0       6-12        -310         375   
3         244        20       17400.0      12-25        -277         378   
4         236       336      313392.0      25-50        -272         390   

   radial  active.region.ar  
0     692                 0  
1     694              9811  
2     487              9825  
3     469              9822  
4     476              9825

In [202]:
df = df.drop('start.date', axis=1)

In [203]:
df = df[df['start.time'] > '2010-12-31 23:59:59']
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 63960 entries, 52183 to 116142
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype         
---  ------            --------------  -----         
 0   start.time        63960 non-null  datetime64[ns]
 1   peak              63960 non-null  datetime64[ns]
 2   end               63960 non-null  datetime64[ns]
 3   duration.s        63960 non-null  int64         
 4   peak.c/s          63960 non-null  int64         
 5   total.counts      63960 non-null  float64       
 6   energy.kev        63960 non-null  object        
 7   x.pos.asec        63960 non-null  int64         
 8   y.pos.asec        63960 non-null  int64         
 9   radial            63960 non-null  int64         
 10  active.region.ar  63960 non-null  int64         
dtypes: datetime64[ns](3), float64(1), int64(6), object(1)
memory usage: 5.9+ MB


In [204]:
# Split the column and convert to eV
df[['energy_low_ev', 'energy_high_ev']] = df['energy.kev'].str.split('-', expand=True).astype(float) * 1000

# Convert to integer
df['energy_low_ev'] = df['energy_low_ev'].astype(int)
df['energy_high_ev'] = df['energy_high_ev'].astype(int)
df = df.drop('energy.kev', axis=1)

In [205]:
df

start.time                peak                 end  \
52183  2011-01-01 00:48:52 2011-01-01 00:51:22 2011-01-01 00:55:44   
52184  2011-01-01 02:58:40 2011-01-01 02:59:22 2011-01-01 03:00:48   
52185  2011-01-01 05:41:04 2011-01-01 05:41:50 2011-01-01 05:44:20   
52186  2011-01-01 05:50:28 2011-01-01 05:56:06 2011-01-01 06:01:44   
52187  2011-01-01 12:01:04 2011-01-01 12:01:38 2011-01-01 12:02:32   
...                    ...                 ...                 ...   
116138 2018-02-09 16:41:28 2018-02-09 16:42:54 2018-02-09 16:43:32   
116139 2018-02-09 18:15:56 2018-02-09 18:17:26 2018-02-09 18:17:40   
116140 2018-02-10 13:04:36 2018-02-10 13:06:46 2018-02-10 13:07:04   
116141 2018-02-26 15:49:56 2018-02-26 15:51:18 2018-02-26 15:53:52   
116142 2018-03-03 04:04:08 2018-03-03 04:06:22 2018-03-03 04:12:20   

        duration.s  peak.c/s  total.counts  x.pos.asec  y.pos.asec  radial  \
52183          412        68       94032.0        -786         515     940   
52184          128        36       20376.0         902         244     935   
52185          196        28       25776.0         904         238     935   
52186          676        34       94416.0        -739         565     930   
52187           88        28        9192.0        -619        -179     645   
...            ...       ...           ...         ...         ...     ...   
116138         124        18        2888.0        -345         -38     347   
116139         104        16        1656.0        -268         -38     271   
116140         148        15        2224.0        -115         -38     121   
116141         236        16        3312.0         115         192     223   
116142         492        42       15816.0         926         128     935   

        active.region.ar  energy_low_ev  energy_high_ev  
52183               1140           6000           12000  
52184               1138           6000           12000  
52185               1138           6000           12000  
52186               1140           6000           12000  
52187                  0           6000           12000  
...                  ...            ...             ...  
116138              2699           6000           12000  
116139              2699           6000           12000  
116140              2699           6000           12000  
116141              2700           6000           12000  
116142              2700           6000           12000  

[63960 rows x 12 columns]

In [206]:
df['energy_low_ev'].unique()

array([  6000,   3000,  12000,  25000,  50000, 100000, 300000])

In [207]:
# Clean the data
def remove_outliers_iqr(df, columns):
    df_cleaned = df.copy()
    
    for column in columns:
        # Calculate Q1 (25th percentile) and Q3 (75th percentile)
        Q1 = df_cleaned[column].quantile(0.25)
        Q3 = df_cleaned[column].quantile(0.75)
        IQR = Q3 - Q1  # Interquartile Range
        
        # Define bounds for outliers
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR
        
        # Remove outliers
        df_cleaned = df_cleaned[(df_cleaned[column] >= lower_bound) & (df_cleaned[column] <= upper_bound)]
        
    return df_cleaned

In [208]:
clean_parameters = df.drop(['start.time', 'peak','end'], axis=1)
df_cleaned = remove_outliers_iqr(df, clean_parameters.columns)

In [209]:
# Split the data
X = df_cleaned.drop(['start.time','peak','end'], axis=1)
y = df_cleaned[['duration.s']]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [210]:
# Scale the training and testing data

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [211]:
X_train_scaled

array([[ 6.83761153e-01,  3.55756492e+00,  2.80002338e+00, ...,
        -1.39635807e+00,  0.00000000e+00,  0.00000000e+00],
       [-1.48335349e+00, -4.51009880e-01, -1.03425959e+00, ...,
         4.36102839e-01,  0.00000000e+00,  0.00000000e+00],
       [-8.50479301e-01, -1.20261765e+00, -1.10715837e+00, ...,
         1.14193963e+00,  0.00000000e+00,  0.00000000e+00],
       ...,
       [-2.58250570e-02, -4.51009880e-01,  1.29814507e-03, ...,
         1.28559552e+00,  0.00000000e+00,  0.00000000e+00],
       [-1.98427108e-01,  4.76013736e+00,  1.41315507e+00, ...,
        -7.97009723e-02,  0.00000000e+00,  0.00000000e+00],
       [-1.15732739e+00, -4.00902695e-01, -8.41332758e-01, ...,
         4.50807772e-01,  0.00000000e+00,  0.00000000e+00]])

In [212]:
knn = KNeighborsRegressor(n_neighbors=3)
knn.fit(X_train_scaled, y_train)
    
# Make predictions on training data (for reference)
train_predictions = knn.predict(X_train_scaled)

# Make predictions on test data (for evaluation)
test_predictions = knn.predict(X_test_scaled)

# Evaluate performance on training data
train_mse = mean_squared_error(y_train, train_predictions)
train_rmse = np.sqrt(train_mse)
print(f'Training Root Mean Squared Error: {train_rmse:.2f}')
print(train_predictions)

Training Root Mean Squared Error: 19.49
[[465.33333333]
 [ 46.66666667]
 [168.        ]
 ...
 [324.        ]
 [284.        ]
 [ 81.33333333]]


In [213]:
comparison_df = pd.DataFrame({
    'Actual Duration(s)': y_test.values.flatten().astype(int),  # Flatten to convert to 1D array
    'Predicted Duration(s)': test_predictions.flatten().astype(int)  # Flatten to convert to 1D array
})

print(comparison_df)

      Actual Duration(s)  Predicted Duration(s)
0                    320                    314
1                    584                    532
2                    676                    632
3                    564                    522
4                     88                    110
...                  ...                    ...
8445                 252                    256
8446                 212                    218
8447                 152                    144
8448                 640                    620
8449                 508                    470

[8450 rows x 2 columns]


In [215]:
with open('regressor.pkl', 'wb') as f:
    pickle.dump(knn, f)
    
with open('scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)